### ISSUE TITLE
Add new option '-d' for mlmmj-make-ml to specify FQDN domain name

### ISSUE THREAD

**Issue by iredmail** [iredmail/openmlmmj#3]
Patch available: http://mlmmj.org/bugs/bug.php?id=65

Latest patch with all 3 options support:

-d: The domain name part of the mailing list
-o: The email address of the list owner
-l: The language of list text template files

**Comment by stappersg** [comment]
The patch is implemented in https://gitlab.com/mlmmj/mlmmj

Actual commit is https://gitlab.com/mlmmj/mlmmj/commit/e0d9aa7e45ba03cd066333ee5bd6a273412e619d

At the MLMMJ mailinglist is currently a thread with subject _Where is upstream?_. 

Please join the new team.
